### ISSUE TITLE
'Falsey' statements don't display in Property Line

### ISSUE THREAD

**Issue by lolbat** [valentine195/obsidian-5e-statblocks#67]
If you have a string that resolves to false in a property line it will not display.

```
saves:
  - Fortitude: +1
  - Reflexes: +1
  - Will: +1
```

In this example all of the saves will display, 

And in this one

```
saves:
  - Fortitude: +1
  - Reflexes: +0
  - Will: +1
```

Reflexes won't display. You need to specifically declare it as a string for it to work

```
saves:
  - Fortitude: +1
  - Reflexes: '+0'
  - Will: +1
```
